log:
  level: DEBUG

entryPoints:
  django:
    address: "localhost:8000"

  traefik-hub:
    address: "localhost:8080"

  flower:
    address: "localhost:5555"

http:
  routers:
    django-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - django
      service: django

    flower-secure-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - flower
      service: flower
  services:
    django:
      loadBalancer:
        servers:
          - url: "http://django:8000"

    flower:
      loadBalancer:
        servers:
          - url: "http://flower:5555"

# providers:
#   # https://docs.traefik.io/master/providers/file/
#   file:
#     filename: /etc/traefik/traefik.yml
#     watch: true
providers:
  docker:
    exposedByDefault: false
