#!/bin/bash

set -o errexit
set -o nounset

/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT --timeout=10 --strict -- echo "postgres is up"

### TEST LIKE PROD
# exec celery -A config.celery_app worker --concurrency 4 --max-tasks-per-child 10 --max-memory-per-child 200000 -P prefork -l INFO

### LOCAL SETTINGS
watchfiles celery.__main__.main --args '-A config.celery_app worker --max-memory-per-child 1000000 --max-tasks-per-child 10 -P prefork -l INFO'

#celery -A config.celery_app worker --loglevel=INFO --concurrency=8 -O fair -P prefork -n cel_app_worker
#celery -A config.celery_app worker --loglevel=INFO --concurrency=8 -P prefork -n cel_app_worker
