#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.server_dev

echo "Make migrations the Database at startup of project"
python /app/manage.py makemigrations

echo "Migrating the Database at startup of project"
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput


echo "Django docker is fully configured successfully."
# Run locally
python manage.py runserver_plus 0.0.0.0:8000

