#!/bin/bash

set -o errexit
set -o nounset

sleep 10
/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT --timeout=10 --strict -- echo "postgres is up"
rm -f './celerybeat.pid'

celery -A config.celery_app beat --max-interval=3600 -l INFO
#celery -A config.celery_app beat -l INFO -f LOGFILE, --logfile='./test.log'
#celery -A robobud.celery worker -f /var/log/celery/%h-%I.log -l info
