#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if ( ! test -f /app/secrets.json ); then
    echo "Secrets file not found, creating..."
    touch /app/secrets.json
fi
cat << EOF > /app/secrets.json 
{
    "Exchange Accounts": {
    }
}
EOF
python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

/usr/bin/litestream replicate