#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

cat << EOF > /app/secrets.json 
{
    "Exchange Accounts": {
    }
}
EOF
/usr/bin/litestream replicate