#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

sleep 10
/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT --timeout=10 --strict -- echo "postgres is up"
rm -f './celerybeat.pid'

# exec celery -A config.celery_app beat -l INFO
celery -A config.celery_app beat --max-interval=3600 -l INFO
