version: '3'

name: napse-dtk-development

volumes:
  napse_dtk_dev_postgres_data: {}
  napse_dtk_dev_postgres_data_backups: {}

services:
  django: &django
    build: 
      context: ..
      dockerfile: ./docker/compose/development/django/Dockerfile
    image: napse_dtk_dev_django
    container_name: napse_dtk_dev_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ../.:/app:z
    env_file:
      - ../.envs/.development/.django
      - ../.envs/.development/.postgres
    command: /start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
      - "traefik.http.routers.django.entrypoints=web"
    expose:
      - "8000"

  postgres:
    build:
      context: ..
      dockerfile: ./docker/compose/development/postgres/Dockerfile
    image: napse_dtk_dev_postgres
    container_name: napse_dtk_dev_postgres
    volumes:
      - napse_dtk_dev_postgres_data:/var/lib/postgresql/data:Z
      - napse_dtk_dev_postgres_data_backups:/backups:z
    env_file:
      - ../.envs/.development/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: napsedjango_local_redis

  celeryworker:
    <<: *django
    image: napse_dtk_dev_celeryworker
    container_name: napse_dtk_dev_celeryworker
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celeryworker
    labels:
      - "traefik.enable=false"

  celerybeat:
    <<: *django
    image: napse_dtk_dev_celerybeat
    container_name: napse_dtk_dev_celerybeat
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celerybeat
    labels:
      - "traefik.enable=false"

  traefik:
    image: "traefik:v2.9.5"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--entrypoints.frontend.address=:3005"
      - "--entrypoints.flower.address=:5555"
    ports:
      - "5555:5555"
      - "8000:8000"
      - "8080:8080"
      - "3005:3005"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

