version: '3'

name: napse-dtk-development-litestream

services:
  django: &django
    build: 
      context: ..
      dockerfile: ./docker/compose/development/django/Dockerfile
    image: napse_dtk_dev_django
    container_name: napse_dtk_dev_django
    # platform: linux/x86_64
    depends_on:
      - redis
    volumes:
      - ../.:/app:z
    env_file:
      - ../.envs/.development/.django
      - ../.envs/.development/.litestream
    command: /start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
      - "traefik.http.routers.django.entrypoints=web"
    expose:
      - "8000"

  minio:
    image: minio/minio
    container_name: napse_dtk_dev_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" 
      - "9001:9001"

  createbuckets:
    image: minio/mc
    container_name: napse_dtk_dev_minio_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing minio/miniobkt;
      mc anonymous set public minio/miniobkt;
      exit 0;
      "

  celeryworker:
    <<: *django
    image: napse_dtk_dev_celeryworker
    container_name: napse_dtk_dev_celeryworker
    depends_on:
      - redis
      - django
    ports: []
    command: /start-celeryworker
    labels:
      - "traefik.enable=false"

  celerybeat:
    <<: *django
    image: napse_dtk_dev_celerybeat
    container_name: napse_dtk_dev_celerybeat
    depends_on:
      - redis
      - django
    ports: []
    command: /start-celerybeat
    labels:
      - "traefik.enable=false"

  flower:
    <<: *django
    image: napse_dtk_dev_flower
    container_name: napse_dtk_dev_flower
    command: /start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`localhost`)"
      - "traefik.http.routers.flower.entrypoints=flower"
    expose:
      - "5555"

  traefik:
    image: "traefik:v2.9.5"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
      - "--entrypoints.frontend.address=:3005"
      - "--entrypoints.flower.address=:5555"
    ports:
      - "5555:5555"
      - "8000:8000"
      - "8080:8080"
      - "3005:3005"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  redis:
    image: redis:6
    container_name: napsedjango_local_redis