version: '3'

volumes:
  napse_dev_tk_local_postgres_data: {}
  napse_dev_tk_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ..
      dockerfile: ./docker/compose/server/django/Dockerfile
    image: napse_dev_tk_server_django
    container_name: napse_dev_tk_server_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.envs/.server/.django
      - ../.envs/.server/.postgres
    command: /start_prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
      - "traefik.http.routers.django.entrypoints=web"
    expose:
      - "8000"

  postgres:
    build:
      context: ..
      dockerfile: ./docker/compose/server/postgres/Dockerfile
    image: napse_dev_tk_server_postgres
    container_name: napse_dev_tk_server_postgres
    volumes:
      - napse_dev_tk_local_postgres_data:/var/lib/postgresql/data:Z
      - napse_dev_tk_local_postgres_data_backups:/backups:z
    env_file:
      - ../.envs/.server/.postgres
    ports:
      - "5432:5432"

  traefik:
    image: "traefik:v2.9.5"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  redis:
    image: redis:6
    container_name: napse_dev_tk_server_redis

  celeryworker:
    <<: *django
    image: napse_dev_tk_server_celeryworker
    container_name: napse_dev_tk_server_celeryworker
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celeryworker
    labels:
      - "traefik.enable=false"

  celerybeat:
    <<: *django
    image: napse_dev_tk_server_celerybeat
    container_name: napse_dev_tk_server_celerybeat
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celerybeat
    labels:
      - "traefik.enable=false"

