#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Make migrations the Database at startup of project"
python manage.py makemigrations

echo "Migrating the Database at startup of project"
python manage.py migrate
python manage.py collectstatic --noinput

echo "Django docker is fully configured successfully."

python manage.py runserver_plus 0.0.0.0:8000
