name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: build
        run: make build
        
    