name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types: 
      - completed

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: | 
          make build-prod

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker image ls
          TAG_NAME=$(grep -oP '(?<=## \[)[^\]]+' CHANGELOG.md | head -n 1)
          VERSION=v$TAG_NAME

          docker tag napse_dtk_prod_litestream ghcr.io/${{ github.repository }}/napse_dtk_prod_litestream:$VERSION
          docker tag napse_dtk_prod_django ghcr.io/${{ github.repository }}/napse_dtk_prod_django:$VERSION

          docker push ghcr.io/${{ github.repository }}/napse_dtk_prod_litestream:$VERSION
          docker push ghcr.io/${{ github.repository }}/napse_dtk_prod_django:$VERSION
