name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types: 
      - completed

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: | 
          make build-prod

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          TAG_NAME=$(grep -oP '(?<=# \[)[^\]]+' CHANGELOG.md | head -n 1)
          echo "Tagging with $TAG_NAME"
          VERSION=v$TAG_NAME
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          docker tag napse_dtk_prod_django ghcr.io/${{ github.repository }}/napse_dtk_prod_django:$VERSION
          docker tag napse_dtk_prod_django ghcr.io/${{ github.repository }}/napse_dtk_prod_django:latest
            
      - name: Push Django Docker image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker push ghcr.io/${{ github.repository }}/napse_dtk_prod_django:${{ env.VERSION }}

      - name: Push Django Docker image latest
        run: |
          docker push ghcr.io/${{ github.repository }}/napse_dtk_prod_django:latest


      - name: Create .zip file
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          make setup-prod
          zip -r deploy-$VERSION.zip provisionEB/**/*
          ls
      
      - name: Push .zip file
        uses: actions/upload-artifact@v2
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: deploy-package-aws-eb:$VERSION
          path: deploy-$VERSION.zip 
