name: Django CI

on:
  pull_request_target:

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true



  build:
    name: Django build
    needs:
      - start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile ./backend/requirements/development.txt --output-file ./full-requirements.txt --resolver=backtracking
          pip install -r ./full-requirements.txt

      - name: Lint with ruff
        run: |
          pip install ruff
          # stop the build if there are Python syntax errors or undefined names
          ruff .

      - name: Tests and coverage
        run: |
          coverage run ./backend/manage.py test -v2 --keepdb && coverage html

      - name: Coverage value 
        run: |
          cvg_result=$(coverage report --skip-covered | head -n -2 | tail -n 1 | awk '{print $NF}' | sed 's/%//')
          echo "COVERAGE=$cvg_result" >> $GITHUB_ENV

      - name: Coverage badge
        if: ${{ github.base_ref == 'main' }} 
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.NAPSE_SECRET_GIST }}
          gistID: 93ea40ff182ebdfede01e2e5f8c711f3
          filename: napse-developer-toolkit-coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}% 
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 50
          maxColorRange: 95
